### ISSUE TITLE
AMC Printing Not in correct Order

### ISSUE THREAD

**Issue by sabinsp09** [azharakbar/lafi-sa.issues#15] opened 2020-06-09 10:50 UTC
**Annual Maintenance Contract Printing Issues**
I noticed some recent issue while printing the AMC.
1- When we give *Print AMC* , the Page Order is changing. First Page is coming as Second and Second page instead of the First, in such a Order.
2- It would be great if you can add page numbers in our Contract.
3- The recently produced AMC, the arabic name was "شركة مصانع الخياط للطوب الاحمر بحرة المحدودة", But in Print The full name is not displayed. Only " شركة مصانع الخياط للطوب الا" is coming.

**To Reproduce**
1. Go to AMC *LS/AMC-22/20*
2. Click on *Print AMC*
3. See error

**Screenshots**
A- The first error Screenshot. which is the second page is showing as first page in print.
[DMT AMC June 2020.pdf](https://github.com/azharakbar/lafi-sa.issues/files/4751679/DMT.AMC.June.2020.pdf)

![image](https://user-images.githubusercontent.com/61094152/84138860-a6784d00-aa57-11ea-9e25-9c2e1b6c1c44.png)

B- Second error, the name is not displayed in full
![image](https://user-images.githubusercontent.com/61094152/84138699-5e592a80-aa57-11ea-8ae6-eec961e86987.png)

**Additional context**
Also creation of AMC date is not mentioned anywhere in the AMC which we already discussed. hope you will add those features with permission of Abdul Majeed.
And Some pages are printing additionally without content along with the AMC which you can eliminate.

The saved PDF is attached with this request for your reference.

**Comment by azharakbar** [comment] 2020-07-02 17:50
Duplicate of #17

**Closed as completed** 2020-08-08 11:14 UTC
Labels: duplicate
