### ISSUE TITLE
Bulk pre-order template upload error

### ISSUE THREAD

**Issue by majeedpalakkal** [azharakbar/lafi-sa.issues#3] opened 2020-02-16 06:42 UTC
Excel template doesn't upload, it's getting an error.
Error message shown below

Fatal error: 'break' not in the 'loop' or 'switch' context in /home2/majeedlafi/public_html/libraries/excel/PHPExcel/Calculation/Functions.php on line 574

**Comment by azharakbar** [comment] 2020-02-16 07:25
@majeedpalakkal 
Pls adhere to the template of NEW ISSUE

Reproduction steps not found
Reproduction steps also include attaching the excel file that produces the error

Pls mention whether reproducing or not in testServer

Follow all these steps in all future issues....Use the template for BUG REPORT to add a new issue

**Comment by majeedpalakkal** [comment] 2020-02-16 08:29
[Panasonic.xlsx](https://github.com/azharakbar/lafi-sa.issues/files/4209504/Panasonic.xlsx)

Reproduction steps
1. https://www.lafi-sa.com/new_test/manage
2. Click "Bulk Pre order entry"
3. Choose the excel template
4. Upload

New_test has the same problem

**Comment by azharakbar** [comment] 2020-02-16 11:35
Duplicate of #4

**Comment by majeedpalakkal** [comment] 2020-02-17 18:28
Yes, It's working fine in New_test now.  You can merge

**Comment by majeedpalakkal** [comment] 2020-02-18 10:42
The bulk pre-order template is able to upload, but it doesn't display in front end

**Comment by azharakbar** [comment] 2020-02-18 17:11
Ok

**Comment by azharakbar** [comment] 2020-02-18 17:21
preOrder feature was not merged properly

**Comment by majeedpalakkal** [comment] 2020-02-19 07:04
Now the pre-order items displaying and working properly.

However, there is another problem related to this.  When the Pre-order items & special offer items active on same time, both together doesn't display in front-end. Please check

**Comment by azharakbar** [comment] 2020-02-19 08:37
@majeedpalakkal pls give more details with screenshots.. Expected screenshots.. And what is the currently displaying screenshots

**Comment by majeedpalakkal** [comment] 2020-02-19 10:34
Really Sorry, it was reported by a mistake by my side.  The solution is OK and working properly.

**Comment by majeedpalakkal** [comment] 2020-02-19 11:11
Please merge it to mainline

**Closed as completed** 2020-02-19 14:41 UTC
Labels: bug, solution-verified
